### ISSUE TITLE
window is not defined error in react

### ISSUE THREAD

**Issue by zluo01** [MoePlayer/react-aplayer#7]
I follow your example on the homepage and get a " window is not defined" error.

"react": "^16.6.3",
 "react-aplayer": "^1.0.0",

error message:
window is not defined
ReferenceError: window is not defined
    at Object.<anonymous> (/home/mike/Documents/mbox/node_modules/aplayer/dist/APlayer.min.js:3:3)
    at Module._compile (internal/modules/cjs/loader.js:722:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:733:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at /home/mike/Documents/mbox/node_modules/react-aplayer/dist/react-aplayer.min.js:1:189
    at Object.<anonymous> (/home/mike/Documents/mbox/node_modules/react-aplayer/dist/react-aplayer.min.js:1:496)
    at Module._compile (internal/modules/cjs/loader.js:722:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:733:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)

code
```
class Player extends React.Component {
    render() {
        const props = {
            fixed: true,
            mini: true,
            listFolded: false,
            lrcType: 3,
            audio: [
                {
                    name: '光るなら',
                    artist: 'Goose house',
                    url: 'https://moeplayer.b0.upaiyun.com/aplayer/hikarunara.mp3',
                    cover: 'https://moeplayer.b0.upaiyun.com/aplayer/hikarunara.jpg',
                    lrc: 'https://moeplayer.b0.upaiyun.com/aplayer/hikarunara.lrc',
                    theme: '#ebd0c2'
                }
            ]
        };
        return (
            <div id={"player"}>
                <ReactAplayer{...props}/>
            </div>
        )
    };
}
export default Player
```

Thank you

**Comment by PiccoloYu** [comment]
me too
